# Generated by Django 4.1.2 on 2022-10-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hoarder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=20)),
                ("subreddit", models.CharField(max_length=21)),
                ("url", models.URLField()),
                ("creation_date_time", models.DateTimeField()),
                ("is_saved", models.BooleanField(default=True)),
                ("over_18", models.BooleanField()),
            ],
        ),
    ]
