# Generated by Django 4.1.2 on 2022-10-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoarder", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hoarder",
            new_name="Post",
        ),
    ]
