# Generated by Django 4.1.2 on 2022-11-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoarder", "0002_rename_hoarder_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="creation_date_time",
            new_name="cdt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="over_18",
        ),
        migrations.AddField(
            model_name="post",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
